# Generated by Django 3.1 on 2020-08-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_description', models.CharField(max_length=255)),
                ('product_price_bs', models.IntegerField(default=0)),
                ('product_price_cop', models.IntegerField(default=0)),
                ('product_price_usd', models.IntegerField(default=0)),
            ],
        ),
    ]
